# ── Auralix Server Properties ──
server-name=Auralix
motd=§bAuralix §7» §aOnline
server-ip=
server-port=25565
online-mode=false
max-players=40
level-name=world
level-seed=
difficulty=normal
gamemode=survival
pvp=true
enable-command-block=false
view-distance=10
simulation-distance=10
white-list=false
enforce-whitelist=false
spawn-protection=16
max-world-size=29999984
allow-nether=true
allow-flight=false
enable-rcon=false
enable-query=false
prevent-proxy-connections=false
